### ISSUE TITLE
help: create private space is empty

### ISSUE THREAD

**Issue by victorlarignon** [ComPlat/ChemistryKnowledgeBase#218]
in th ehelp menu on top of the wiki pages, there is a help: create private space option which leads to an empty page. We should either create the page or remove it from the menu. (I'm not sure that this functionality is usefull for users, so probably remove it)

**Comment by kkthek** [comment]
I fixed the bug that the private wiki is empty.

**Comment by kkthek** [comment]
the help page was created by victor.
