### ISSUE TITLE
Import investigation as CSV

### ISSUE THREAD

**Issue by kkthek** [ComPlat/ChemistryKnowledgeBase#222]
Import investigation type as CSV file.

* assumption: user knows the type of investigation and can specified this on import.

* Header names in CSV should match property names in the wiki. this makes it easy to add new properties if necessary.
* Molecules are identified by inchi-key
* Non-existing molecules need to be fully specified. could be a separate-column with same name but a prefix "MOL-<property-name>"
* **Problem**: we need molfile (due to current rendering service) which contains line feeds. this does not fit in a CSV file.

A possible solution is to have the molecules as separate files referenced in the CSV file by the filename. We could group them in a zip file for easy handling.

**Comment by nicolejung** [comment]
Could be excel an alternative to csv? This would omit the issue of the molfile and is more user friendly - could that work with the Wiki?

**Comment by kkthek** [comment]
Usecase 1 & 2 implemented.

**Comment by kkthek** [comment]
close this for now and put the ELN import into separate ticket.
