### ISSUE TITLE
New columns in the CO2 reduction table 

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/ChemistryKnowledgeBase#228]
We need a new column "feedstock volume" next to the feedstock gas column. Header could be volume and info in hover over "volume of feedstock gas". The unit of the volume should be mL. 
We need an new column with  "intensity" (header)  in "kW/m²" as a unit. Hover over in the header "light intensity"

**Comment by kkthek** [comment]
done. Two new properties added:

* Feedstock volume
* Intensity

Both are per default hidden in investigation links.
