### ISSUE TITLE
DOI check

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/ChemistryKnowledgeBase#250]
I would be great to have a DOI check while creating new entries to avoid duplicates due to small changes in the title of publications. 
- Creation of a new publication page -> check for DOI if the DOI is given -> if a publication page related to the DOI is available warning and hint to use/edit the existing publication page (with citing the title to facilitate to find it).

**Comment by kkthek** [comment]
done. If the DOI is already used on a publication, the user gets a notice with a link to that publication.
