### ISSUE TITLE
save units as metadata

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/ChemistryKnowledgeBase#255]
e.g. TON/h oder TON/min as units for TOF

**Comment by kkthek** [comment]
I added the units annotation but need support to specify the units for these properties:

https://chemwiki.scc.kit.edu/main/mediawiki/index.php?title=Special:Ask&x=-5B-5BUnit%3A%3A-2Dto-20be-20set-2D-5D-5D&format=broadtable&limit=200&link=all&headers=show&searchlabel=...%20further%20results&class=sortable%20wikitable%20smwtable&sort=&order=asc&offset=0&mainlabel=

**Comment by nicolejung** [comment]
I think, we need a clearer definition of some of the units as they are not defined in a ways that one can give the unit in a general manner, e.g. "concentration" depends on the setting -> I think we need further discussions

**Comment by kkthek** [comment]
I will discuss this issue with Michael and provide a plan how to handle different units of measurement in forms and tables.

**Comment by kkthek** [comment]
we will do the changes as part of ticket #274. So I close this for now.
