### ISSUE TITLE
löschen alter Investigations auf Publication-Page

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/ChemistryKnowledgeBase#267]
Aktuell werden alle Investigations, die über die eine Publikationsseite hochgeladen wurden, auch dort als Investigations angezeigt - allerdings werden sie dies immernoch, auch wenn die Investigations gelöscht werden (die Liste sollte dann auch bereinigt werden)
https://chemwiki.scc.kit.edu/main/mediawiki/Exchange_Coupling_Determines_Metal-Dependent_Efficiency_for_Iron-_and_Cobalt-Catalyzed_Photochemical_CO2_Reduction

**Comment by kkthek** [comment]
On page-save it is now checked if there are unused investigations. If so the are removed from the wiki.
