### ISSUE TITLE
capitalize error

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/ChemistryKnowledgeBase#270]
found the following issue in CV test: "Argon" is not in the list (nitrogen, argon, CO2, CO, O2, H2, none) of [allowed values](https://chemwiki.scc.kit.edu/main/mediawiki/Property:Allows_value) for the "Gas" property.

**Comment by kkthek** [comment]
fixed: argon -> Argon, nitrogen -> Nitrogen
