### ISSUE TITLE
molecule without image

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/ChemistryKnowledgeBase#271]
https://chemwiki.scc.kit.edu/main/mediawiki/Molecule:100939
https://chemwiki.scc.kit.edu/main/mediawiki/Molecule:100963
die folgenden scheinen durch einen Import entstanden zu sein: 
https://chemwiki.scc.kit.edu/main/mediawiki/Molecule:100973
https://chemwiki.scc.kit.edu/main/mediawiki/Molecule:100974
https://chemwiki.scc.kit.edu/main/mediawiki/Molecule:100975
https://chemwiki.scc.kit.edu/main/mediawiki/Molecule:100976
https://chemwiki.scc.kit.edu/main/mediawiki/Molecule:100977

**Comment by nicolejung** [comment]
another one here: 
https://chemwiki.scc.kit.edu/main/mediawiki/Molecule:100963

**Comment by kkthek** [comment]
die ersten beiden sind repariert. da hat das molfile gefehlt. die anderen sind aufgrund eines fehlerhaften Imports entstanden. Da sind die Spalten im Excel durcheinander gekommen.
